- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mogodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: update mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: restart mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download the Mongodb content and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    dest: /tmp
    remote_src: yes


- name: Load schema
  community.mongodb.mongodb.shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idemponent: yes
  loop:
      - catalogue
      - users