- name: copy MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install MySQL server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: install MySQL python  server
  ansible.builtin.yum:
    name: MySQL-python
    state: installed

- name: Start MySql Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: check root default password
  block:
    - name: Get my sql version to get the DB connection
      mysql_info:
        login_user: root
        login_password: "{{MYSQL_PASSWORD}}"
        filter: version
  rescue:
    - name : Load MYSQL Log file
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

- name: Declare facts
  ansible.builtin.set_fact:
    Default_pass: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') | split(' ') | last }}"

- name: Change MySQL
  ansible.builtin.shell: echo "Alter USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASSWORD}}';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASS}}"
  ignore_errors: yes

- name: Download the MYSQL content and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
    dest: /tmp
    remote_src: yes


- name: Load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"






