- name: setup nodejs repsos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add RoboShop App User
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Application User

-  name: remove the old App content
   ansible.builtin.file:
     path: /home/roboshop/catalogue
     state: absent

- name: Download the catalogue content and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: copy catalogue content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes
  become_user: roboshop

- name: install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Restart catalogue
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon-reload: yes