- name: add roboshopuser
  ansible.builtin.user:
    name: roboshop
    comment: roboshop application user

- name: remove old app content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Download frontend and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: copy the content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop
