- name: setup nodejs repsos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: include the app pre setup
  ansible.builtin.include_role:
    name: common
    tasks_from: app-pre-setup


- name: Install Nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: include systemd
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

